version: '3'

services:
  apache:
    build:
      context: ./docker/apache
    volumes:
      - /Users/ruthnewman/documents/stellar/www:/var/www/app/public/
    ports:
      - 3306:80
    links:
      - php
  php:
    build:
      context: ./docker/php
    links:
      - mysql
    volumes:
      - /Users/ruthnewman/documents/stellar/www:/var/www/app/public/
    working_dir: /var/www/public
  mysql:
    image: mysql:5.6
    ports:
      - 14406:3306
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=stellar
    volumes:
        - ./application/db:/docker-entrypoint-initdb.d
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
       - mysql
    ports:
       - 19090:80
  sass:
    build:
      context: ./docker/sass
    volumes:
      - './www/public/assets:/sass'
    command: sass --watch sass:css
    working_dir: /sass